import { Service } from "./types";

export const mockServices: Service[] = [
  {
    id: "1",
    title: "Serviço de Limpeza Residencial Completo",
    description: "Ofereço serviços de limpeza residencial completa, incluindo cozinha, banheiros, quartos e áreas comuns. Trabalho com produtos de qualidade e atenção aos detalhes.",
    category: "Limpeza",
    providerName: "Maria Silva",
    providerAvatar: "https://github.com/maxleiter.png",
    rating: 5.0,
    price: 150.00,
    city: "Rio de Janeiro",
    estado: "rioDeJaneiro",
    verified: true,
  },
  {
    id: "2",
    title: "Cuidados com Idosos e Acompanhamento",
    description: "Profissional experiente em cuidados com idosos, oferecendo acompanhamento médico, auxílio nas atividades diárias e companhia. Disponibilidade integral.",
    category: "Cuidados",
    providerName: "Ana Costa",
    providerAvatar: "https://github.com/maxleiter.png",
    rating: 4.8,
    price: 200.00,
    city: "São Paulo",
    estado: "saoPaulo",
    verified: true,
  },
  {
    id: "3",
    title: "Serviços de Carpintaria e Marcenaria",
    description: "Carpinteiro especializado em móveis sob medida, reparos e instalações. Trabalho com madeiras nobres e garantia de qualidade em todos os serviços.",
    category: "Carpinteiro",
    providerName: "João Santos",
    providerAvatar: "https://github.com/maxleiter.png",
    rating: 4.9,
    price: 300.00,
    city: "Rio de Janeiro",
    estado: "rioDeJaneiro",
    verified: true,
  },
  {
    id: "4",
    title: "Pintura Residencial e Comercial",
    description: "Pintor profissional com experiência em pintura interna e externa. Trabalho com tintas de primeira linha e acabamento impecável. Orçamento sem compromisso.",
    category: "Pintor",
    providerName: "Carlos Oliveira",
    providerAvatar: "https://github.com/maxleiter.png",
    rating: 4.7,
    price: 250.00,
    city: "São Paulo",
    estado: "saoPaulo",
    verified: false,
  },
  {
    id: "5",
    title: "Serviços de Encanamento 24h",
    description: "Encanador disponível 24 horas para emergências e reparos. Atendo vazamentos, entupimentos, instalações e manutenções preventivas.",
    category: "Encanador",
    providerName: "Pedro Alves",
    providerAvatar: "https://github.com/maxleiter.png",
    rating: 5.0,
    price: 180.00,
    city: "Rio de Janeiro",
    estado: "rioDeJaneiro",
    verified: true,
  },
  {
    id: "6",
    title: "Mecânico Automotivo Especializado",
    description: "Mecânico com mais de 15 anos de experiência. Atendo todos os tipos de veículos, desde manutenção preventiva até reparos complexos. Oficina equipada.",
    category: "Mecânico",
    providerName: "Roberto Lima",
    providerAvatar: "https://github.com/maxleiter.png",
    rating: 4.9,
    price: 350.00,
    city: "São Paulo",
    estado: "saoPaulo",
    verified: true,
  },
  {
    id: "7",
    title: "Fotografia de Eventos e Ensaios",
    description: "Fotógrafo profissional especializado em eventos, casamentos, aniversários e ensaios fotográficos. Equipamento de última geração e edição profissional incluída.",
    category: "Fotógrafo",
    providerName: "Lucas Ferreira",
    providerAvatar: "https://github.com/maxleiter.png",
    rating: 5.0,
    price: 500.00,
    city: "Rio de Janeiro",
    estado: "rioDeJaneiro",
    verified: true,
  },
  {
    id: "8",
    title: "Limpeza Pós-Obra e Reforma",
    description: "Especializado em limpeza pesada pós-obra, removendo resíduos de construção, poeira e sujeira acumulada. Equipamentos profissionais e equipe treinada.",
    category: "Limpeza",
    providerName: "Fernanda Rocha",
    providerAvatar: "https://github.com/maxleiter.png",
    rating: 4.8,
    price: 200.00,
    city: "São Paulo",
    estado: "saoPaulo",
    verified: true,
  },
];

